Repository IdentityServer/IdentityServer4, pull requests merged in 2018-10, with the labels that each got.

#2545 Make some internal types public to facilitate custom service implementations
  src/Constants.cs
  src/Extensions/ClientExtensions.cs
  src/Extensions/IdentityServerToolsExtensions.cs
  src/IdentityServerConstants.cs
  src/Models/TokenCreationRequest.cs
  src/Services/Default/DefaultTokenService.cs
  src/Validation/Default/TokenValidator.cs
Labels: enhancement

#2658 Corrected internal value for ParsedSecretTypes.JwtBearer
  src/IdentityServerConstants.cs
Labels: bug

#2617 Change: error code in TokenValidator class
  src/Validation/Default/TokenValidator.cs
Labels: enhancement, investigating

#2729 Add null check on Consent page
  host/Quickstart/Consent/ConsentController.cs
Labels: bug
