Repository IdentityServer/IdentityServer4, pull requests merged in 2018-09, with the labels that each got.

#2593 Switch to new cake build version
  build.ps1
  build.sh
  build2.ps1
  build2.sh
Labels: enhancement

#2597 Add strong name
  key.snk
  src/IdentityServer4.csproj
  src/Properties/AssemblyInfo.cs
  test/IdentityServer.IntegrationTests/IdentityServer.IntegrationTests.csproj
  test/IdentityServer.UnitTests/IdentityServer.UnitTests.csproj
Labels: new feature

#2604 Create jwk document when signing with JsonWebKey
  src/ResponseHandling/Default/DiscoveryResponseGenerator.cs
Labels: bug

#2611 Update secrets.rst
  docs/topics/secrets.rst
Labels: enhancement
