Repository IdentityServer/IdentityServer4, pull requests merged in 2019-08, with the labels that each got.

#3511 Add support for additional signing algorithms
  src/Directory.Build.targets
  src/IdentityServer4/src/Configuration/CryptoHelper.cs
  src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Crypto.cs
  src/IdentityServer4/src/IdentityServerConstants.cs
  src/IdentityServer4/src/Models/TokenCreationRequest.cs
  src/IdentityServer4/src/ResponseHandling/Default/AuthorizeResponseGenerator.cs
  src/IdentityServer4/src/ResponseHandling/Default/DiscoveryResponseGenerator.cs
  src/IdentityServer4/src/ResponseHandling/Default/TokenResponseGenerator.cs
  src/IdentityServer4/src/Services/Default/DefaultTokenService.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Conformance/Basic/CodeFlowTests.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Endpoints/Authorize/JwtRequestAuthorizeTests.cs
  src/Storage/src/Models/AuthorizationCode.cs
Labels: breaking change

#3514 Update to IdentityModel v4
  src/Directory.Build.targets
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ClientAssertionClient.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Conformance/Basic/ClientAuthenticationTests.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Endpoints/Revocation/RevocationTests.cs
Labels: breaking change

#3517 Move HTTP context accessor access to a later point in JwtRequestValidator
  src/IdentityServer4/src/Validation/Default/JwtRequestValidator.cs
Labels: bug

#3513 Set typ header for access tokens
  samples/Clients/src/SampleApi/Startup.cs
  src/IdentityServer4/src/Configuration/DependencyInjection/Options/IdentityServerOptions.cs
  src/IdentityServer4/src/Services/Default/DefaultTokenCreationService.cs
  src/IdentityServer4/src/Services/Default/DefaultTokenService.cs
  src/IdentityServer4/src/Validation/Default/TokenValidator.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ClientAssertionClient.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ClientCredentialsClient.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/CustomTokenResponseClients.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ExtensionGrantClient.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ResourceOwnerClient.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/Setup/Clients.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/Setup/Scopes.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Endpoints/Introspection/IntrospectionTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/AccessTokenValidation.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Labels: breaking change

#3561 Support specific signing algorithms per validation key
  src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Crypto.cs
  src/IdentityServer4/src/Models/SecurityKeyInfo.cs
  src/IdentityServer4/src/ResponseHandling/Default/DiscoveryResponseGenerator.cs
  src/IdentityServer4/src/Services/Default/DefaultKeyMaterialService.cs
  src/IdentityServer4/src/Services/IKeyMaterialService.cs
  src/IdentityServer4/src/Stores/Default/DefaultValidationKeysStore.cs
  src/IdentityServer4/src/Stores/IValidationKeysStore.cs
  src/IdentityServer4/src/Validation/Default/TokenValidator.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Labels: breaking change

#3563 Emit Integer64 for Epoch Time
  src/IdentityServer4/src/Hosting/IdentityServerAuthenticationService.cs
  src/IdentityServer4/src/Services/Default/DefaultBackChannelLogoutService.cs
  src/IdentityServer4/src/Services/Default/DefaultClaimsService.cs
  src/IdentityServer4/src/Services/Default/DefaultTokenService.cs
  src/IdentityServer4/src/Validation/Default/TokenValidator.cs
  src/IdentityServer4/src/Validation/Models/GrantValidationResult.cs
Labels: enhancement

#3523 move logging before removal so the PromptMode is included in the logging
  src/IdentityServer4/src/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs
Labels: enhancement
