Repository IdentityServer/IdentityServer4, pull requests merged in 2019-12, with the labels that each got.

#3940 Added MS fix for SameSite Cookies to host
  src/IdentityServer4/host/Extensions/SameSiteHandlingExtensions.cs
  src/IdentityServer4/host/Startup.cs
Labels: enhancement

#3935 Fix user code param name in DeviceController
  samples/Quickstarts/2_InteractiveAspNetCore/src/IdentityServer/Quickstart/Device/DeviceController.cs
  samples/Quickstarts/3_AspNetCoreAndApis/src/IdentityServer/Quickstart/Device/DeviceController.cs
  samples/Quickstarts/4_EntityFramework/src/IdentityServer/Quickstart/Device/DeviceController.cs
  src/AspNetIdentity/host/Quickstart/Device/DeviceController.cs
  src/EntityFramework/host/Quickstart/Device/DeviceController.cs
  src/IdentityServer4/host/Quickstart/Device/DeviceController.cs
Labels: bug

#3887 V4: Make client claims serialization friendly
  src/EntityFramework.Storage/src/Mappers/ClientMapperProfile.cs
  src/EntityFramework.Storage/test/IntegrationTests/Stores/ClientStoreTests.cs
  src/IdentityServer4/host/appsettings.json
  src/IdentityServer4/src/Validation/Models/ValidatedRequest.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Services/Default/DefaultClaimsServiceTests.cs
  src/Storage/src/Models/Client.cs
  src/Storage/src/Models/ClientClaim.cs
Labels: breaking change

#3892 V4: Multiple signing keys
  samples/Clients/src/WindowsConsoleSystemBrowser/Program.cs
  src/EntityFramework.Storage/src/Entities/ApiResource.cs
  src/EntityFramework.Storage/src/Entities/Client.cs
  src/EntityFramework.Storage/src/Extensions/ModelBuilderExtensions.cs
  src/EntityFramework.Storage/src/Mappers/AllowedSigningAlgorithmsConverter.cs
  src/EntityFramework.Storage/src/Mappers/ApiResourceMapperProfile.cs
  src/EntityFramework.Storage/src/Mappers/ClientMapperProfile.cs
  src/IdentityServer4/host/Configuration/Clients.cs
  src/IdentityServer4/host/Configuration/Resources.cs
  src/IdentityServer4/host/Startup.cs
  src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Crypto.cs
  src/IdentityServer4/src/Extensions/ApiResourceExtensions.cs
  src/IdentityServer4/src/Extensions/ResourceExtensions.cs
  src/IdentityServer4/src/ResponseHandling/Default/AuthorizeResponseGenerator.cs
  src/IdentityServer4/src/ResponseHandling/Default/DiscoveryResponseGenerator.cs
  src/IdentityServer4/src/Services/Default/DefaultKeyMaterialService.cs
  src/IdentityServer4/src/Services/Default/DefaultTokenCreationService.cs
  src/IdentityServer4/src/Services/Default/DefaultTokenService.cs
  src/IdentityServer4/src/Services/IKeyMaterialService.cs
  src/IdentityServer4/src/Stores/InMemory/InMemorySigningCredentialsStore.cs
  src/IdentityServer4/src/Stores/InMemory/InMemoryValidationKeysStore.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpointTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Extensions/ApiResourceSigningAlgorithmSelectionTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/IdentityServer.UnitTests.csproj
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
  src/Storage/src/Models/ApiResource.cs
  src/Storage/src/Models/Client.cs
  src/Storage/src/Models/Resource.cs
  src/Storage/src/Models/Token.cs
Labels: breaking change, enhancement

#3939 Update PKCE and Consent default settings on Client
  src/EntityFramework.Storage/src/Entities/Client.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Conformance/Basic/ClientAuthenticationTests.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Conformance/Basic/CodeFlowTests.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Conformance/Basic/RedirectUriTests.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Conformance/Basic/ResponseTypeResponseModeTests.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Endpoints/Authorize/RestrictAccessTokenViaBrowserTests.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Endpoints/Revocation/RevocationTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Services/Default/DefaultConsentServiceTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/Setup/TestClients.cs
  src/Storage/src/Models/Client.cs
Labels: breaking change

#3692 Removed obsolete code
  src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer4/src/Configuration/DependencyInjection/Options/AuthenticationOptions.cs
  src/IdentityServer4/src/Hosting/IdentityServerAuthenticationService.cs
  src/IdentityServer4/src/Infrastructure/BackChannelHttpClient.cs
  src/IdentityServer4/src/Services/Default/DefaultUserSession.cs
  src/IdentityServer4/src/Validation/Default/DefaultClientConfigurationValidator.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Common/MockHttpContextAccessor.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Services/Default/DefaultUserSessionTests.cs
Labels: enhancement
