Repository IdentityServer/IdentityServer4, pull requests merged in 2020-03, with the labels that each got.

#4153 private_key_jwt updates
  samples/Clients/src/ConsolePrivateKeyJwtClient/Program.cs
  src/IdentityServer4/host/Configuration/Clients.cs
  src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Additional.cs
  src/IdentityServer4/src/Services/Default/DefaultReplayCache.cs
  src/IdentityServer4/src/Services/IReplayCache.cs
  src/IdentityServer4/src/Validation/Default/JwtRequestValidator.cs
  src/IdentityServer4/src/Validation/Default/PrivateKeyJwtSecretValidator.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ClientAssertionClient.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/Setup/Startup.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs
Labels: enhancement

#3982 Added warning for using your own IUserClaimsPrincipalFactory
  docs/reference/aspnet_identity.rst
Labels: pinned

#3981 Updated cache expiration to use current time
  src/IdentityServer4/src/Services/Default/DistributedDeviceFlowThrottlingService.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Services/Default/DistributedDeviceFlowThrottlingServiceTests.cs
Labels: bug

#3979 Added notification for device code removal
  src/EntityFramework.Storage/src/TokenCleanup/IOperationalStoreNotification.cs
  src/EntityFramework.Storage/src/TokenCleanup/TokenCleanupService.cs
  src/EntityFramework/host/TestOperationalStoreNotification.cs
Labels: pinned

#3965 Fix the name of logout context class in sign-out doc
  docs/topics/signout.rst
Labels: pinned

#4026 Added AddUserSession extension method
  src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Additional.cs
Labels: enhancement

#4202 include sid (if present) in access tokens #3955
  src/IdentityServer4/src/Services/Default/DefaultTokenService.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Services/Default/DefaultTokenServiceTests.cs
Labels: enhancement

#4095 Return invalid_grant when redirect_uri is invalid on token endpoint
  src/IdentityServer4/src/Validation/Default/TokenRequestValidator.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/TokenRequest Validation/TokenRequestValidation_Code_Invalid.cs
Labels: bug

#4227 switch to named HTTP clients from factory (instead of typed)
  src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Additional.cs
  src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer4/src/IdentityServerConstants.cs
  src/IdentityServer4/src/Services/Default/BackChannelLogoutHttpClient.cs
  src/IdentityServer4/src/Services/Default/JwtRequestUriHttpClient.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Labels: enhancement, ready

#4226 Reduce usage of Newtonsoft.Json
  src/IdentityServer4/src/Endpoints/AuthorizeCallbackEndpoint.cs
  src/IdentityServer4/src/Endpoints/Results/ConsentPageResult.cs
  src/IdentityServer4/src/Endpoints/Results/DiscoveryDocumentResult.cs
  src/IdentityServer4/src/Endpoints/Results/IntrospectionResult.cs
  src/IdentityServer4/src/Endpoints/Results/LoginPageResult.cs
  src/IdentityServer4/src/Endpoints/Results/TokenErrorResult.cs
  src/IdentityServer4/src/Endpoints/Results/TokenResult.cs
  src/IdentityServer4/src/Events/Infrastructure/Event.cs
  src/IdentityServer4/src/Extensions/ClaimsExtensions.cs
  src/IdentityServer4/src/Extensions/DictionaryExtensions.cs
  src/IdentityServer4/src/Extensions/NameValueCollectionExtensions.cs
  src/IdentityServer4/src/Extensions/X509CertificateExtensions.cs
  src/IdentityServer4/src/Infrastructure/NameValueCollectionConverter.cs
  src/IdentityServer4/src/Infrastructure/ObjectSerializer.cs
  src/IdentityServer4/src/Logging/LogSerializer.cs
  src/IdentityServer4/src/Models/Messages/Message.cs
  src/IdentityServer4/src/Services/Default/OidcReturnUrlParser.cs
  src/IdentityServer4/src/Stores/Default/DistributedCacheAuthorizationParametersMessageStore.cs
  src/IdentityServer4/src/Stores/Default/QueryStringAuthorizationParametersMessageStore.cs
  src/IdentityServer4/src/Stores/IAuthorizationParametersMessageStore.cs
  src/IdentityServer4/src/Validation/Models/ResourceValidationRequest.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/UserInfoClient.cs
Labels: enhancement

#4208 add support for handling multiple prompt values
  src/IdentityServer4/src/Endpoints/Results/AuthorizeResult.cs
  src/IdentityServer4/src/Extensions/ValidatedAuthorizeRequestExtensions.cs
  src/IdentityServer4/src/Logging/Models/AuthorizeRequestValidationLog.cs
  src/IdentityServer4/src/Models/Messages/AuthorizationRequest.cs
  src/IdentityServer4/src/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs
  src/IdentityServer4/src/Validation/Default/AuthorizeRequestValidator.cs
  src/IdentityServer4/src/Validation/Models/ValidatedAuthorizeRequest.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Endpoints/Results/AuthorizeResultTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/ResponseHandling/AuthorizeInteractionResponseGenerator/AuthorizeInteractionResponseGeneratorTests_Consent.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/ResponseHandling/AuthorizeInteractionResponseGenerator/AuthorizeInteractionResponseGeneratorTests_Login.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Invalid.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Valid.cs
Labels: enhancement

#4204 Add API to interaction service to return error to client
  src/AspNetIdentity/host/Quickstart/Account/AccountController.cs
  src/AspNetIdentity/host/Quickstart/Consent/ConsentController.cs
  src/AspNetIdentity/host/Quickstart/Device/DeviceController.cs
  src/EntityFramework/host/Quickstart/Account/AccountController.cs
  src/EntityFramework/host/Quickstart/Account/ExternalController.cs
  src/EntityFramework/host/Quickstart/Consent/ConsentController.cs
  src/EntityFramework/host/Quickstart/Device/DeviceController.cs
  src/EntityFramework/host/Quickstart/Extensions.cs
  src/IdentityServer4/host/Quickstart/Account/AccountController.cs
  src/IdentityServer4/host/Quickstart/Consent/ConsentController.cs
  src/IdentityServer4/host/Quickstart/Device/DeviceController.cs
  src/IdentityServer4/src/Endpoints/Results/AuthorizeResult.cs
  src/IdentityServer4/src/Models/Messages/ConsentResponse.cs
  src/IdentityServer4/src/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs
  src/IdentityServer4/src/Services/Default/DefaultIdentityServerInteractionService.cs
  src/IdentityServer4/src/Services/IIdentityServerInteractionService.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Services/Default/DefaultIdentityServerInteractionServiceTests.cs
Labels: enhancement

#4203 Improve query on cors origins. #3395
  src/EntityFramework.Storage/migrations/SqlServer/createdb.bat
  src/EntityFramework.Storage/src/DbContexts/ConfigurationDbContext.cs
  src/EntityFramework.Storage/src/Interfaces/IConfigurationDbContext.cs
  src/EntityFramework/host/Properties/launchSettings.json
  src/EntityFramework/migrations/SqlServer/Configuration/ClientsConsole.cs
  src/EntityFramework/migrations/SqlServer/Configuration/ClientsWeb.cs
  src/EntityFramework/migrations/SqlServer/Configuration/Resources.cs
  src/EntityFramework/src/Services/CorsPolicyService.cs
Labels: enhancement

#4235 end session changes: IsActive no longer called and no longer default to a single redirect uri
  src/IdentityServer4/src/Validation/Default/EndSessionRequestValidator.cs
  src/IdentityServer4/src/Validation/Default/TokenValidator.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Endpoints/EndSession/EndSessionTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/EndSessionRequestValidation/EndSessionRequestValidatorTests.cs
Labels: enhancement

#4237 Make aspid profile service more extensible
  samples/Clients/src/MvcCode/Startup.cs
  src/AspNetIdentity/host/Configuration/ClientsConsole.cs
  src/AspNetIdentity/host/Configuration/ClientsWeb.cs
  src/AspNetIdentity/host/Configuration/Resources.cs
  src/AspNetIdentity/src/ProfileService.cs
Labels: enhancement

#4234 Use non-case sensitive string for any ids
  src/IdentityServer4/host/Startup.cs
  src/IdentityServer4/src/Configuration/CryptoHelper.cs
  src/IdentityServer4/src/Extensions/ValidatedAuthorizeRequestExtensions.cs
  src/IdentityServer4/src/Services/Default/DefaultBackChannelLogoutService.cs
  src/IdentityServer4/src/Services/Default/DefaultHandleGenerationService.cs
  src/IdentityServer4/src/Services/Default/DefaultTokenService.cs
  src/IdentityServer4/src/Services/Default/DefaultUserSession.cs
  src/IdentityServer4/src/Test/TestUserStore.cs
Labels: enhancement

#3824 Added ISecretsListParser, ISecretsListValidator interfaces
  src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer4/src/ResponseHandling/Default/DiscoveryResponseGenerator.cs
  src/IdentityServer4/src/Validation/Default/ApiSecretValidator.cs
  src/IdentityServer4/src/Validation/Default/ClientSecretValidator.cs
  src/IdentityServer4/src/Validation/Default/SecretParser.cs
  src/IdentityServer4/src/Validation/Default/SecretValidator.cs
  src/IdentityServer4/src/Validation/ISecretsListParser.cs
  src/IdentityServer4/src/Validation/ISecretsListValidator.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/Secrets/SecretValidation.cs
Labels: feature request, needs discussion, pinned
