Repository IdentityServer/IdentityServer4, pull requests merged in 2020-04, with the labels that each got.

#4223 Correct launchSettings.json link to point to API project
  docs/quickstarts/1_client_credentials.rst
Labels: pinned

#4290 Fix cnf format for MTLS
  samples/Clients/src/SampleApi/ConfirmationValidationMiddleware.cs
  src/IdentityServer4/src/Extensions/X509CertificateExtensions.cs
Labels: bug

#4335 Remove public origin setting
  src/IdentityServer4/src/Configuration/DependencyInjection/Options/IdentityServerOptions.cs
  src/IdentityServer4/src/Configuration/IdentityServerApplicationBuilderExtensions.cs
  src/IdentityServer4/src/Hosting/BaseUrlMiddleware.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Pipeline/ConfigurationTests.cs
Labels: breaking change
