Repository IdentityServer/IdentityServer4, pull requests merged in 2020-09, with the labels that each got.

#4811 Updating resources.rst documentation file
  docs/topics/resources.rst
Labels: pinned

#4706 Example request: included content-type info
  docs/endpoints/token.rst
Labels: docs

#4712 fix multiple WWW-Authenticate header to one
  src/IdentityServer4/src/Endpoints/Results/ProtectedResourceErrorResult.cs
Labels: bug

#4744 Introduce LoggingOptions.AuthorizeRequestSensitiveValuesFilter
  src/IdentityServer4/src/Configuration/DependencyInjection/Options/LoggingOptions.cs
  src/IdentityServer4/src/Endpoints/AuthorizeCallbackEndpoint.cs
  src/IdentityServer4/src/Endpoints/AuthorizeEndpoint.cs
  src/IdentityServer4/src/Endpoints/AuthorizeEndpointBase.cs
  src/IdentityServer4/src/Logging/Models/AuthorizeRequestValidationLog.cs
  src/IdentityServer4/src/Validation/Default/AuthorizeRequestValidator.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Endpoints/Authorize/AuthorizeCallbackEndpointTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Endpoints/Authorize/AuthorizeEndpointBaseTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Endpoints/Authorize/AuthorizeEndpointTests.cs
Labels: enhancement

#4849 fix bug for consent is saved regardless of RememberConsent
  src/IdentityServer4/src/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/ResponseHandling/AuthorizeInteractionResponseGenerator/AuthorizeInteractionResponseGeneratorTests_Consent.cs
Labels: bug

#4850 ensure consumed time is utc
  src/IdentityServer4/src/Services/Default/DefaultRefreshTokenService.cs
Labels: bug

#4851 fix serialization bug on LogoutRequest.Parameters #4655
  src/IdentityServer4/src/Models/Messages/LogoutRequest.cs
Labels: bug

#4854 only re-issue session cookie when client added #4812
  src/IdentityServer4/src/Services/Default/DefaultUserSession.cs
Labels: bug

#4853 add more defensive check on check session endpoint #4051
  src/IdentityServer4/src/Endpoints/Results/CheckSessionResult.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Endpoints/Results/CheckSessionResultTests.cs
Labels: enhancement

#4852 add defensive check to fix bug for when session is expired #4844
  src/IdentityServer4/src/Services/Default/DefaultUserSession.cs
Labels: bug

#4841 InitializeDatabase() fix
  docs/quickstarts/5_entityframework.rst
Labels: docs

#4794 Add missing awaits on CachingClientStore and CachingResourceStore
  src/IdentityServer4/src/Stores/Caching/CachingClientStore.cs
  src/IdentityServer4/src/Stores/Caching/CachingResourceStore.cs
Labels: enhancement

#4868 Make identity server work with publish single file in .NET 5.0
  src/IdentityServer4/src/Configuration/IdentityServerApplicationBuilderExtensions.cs
Labels: enhancement
