Repository IdentityServer/IdentityServer4, pull requests merged in 2020-06, with the labels that each got.

#4504 Update error handling for invalid response modes
  src/IdentityServer4/src/Validation/Default/AuthorizeRequestValidator.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Invalid.cs
Labels: enhancement

#4502 Update form content check to reject multipart forms
  src/IdentityServer4/src/Endpoints/AuthorizeEndpoint.cs
  src/IdentityServer4/src/Endpoints/DeviceAuthorizationEndpoint.cs
  src/IdentityServer4/src/Endpoints/IntrospectionEndpoint.cs
  src/IdentityServer4/src/Endpoints/TokenEndpoint.cs
  src/IdentityServer4/src/Endpoints/TokenRevocationEndpoint.cs
  src/IdentityServer4/src/Extensions/HttpRequestExtensions.cs
  src/IdentityServer4/src/Validation/Default/BearerTokenUsageValidator.cs
  src/IdentityServer4/src/Validation/Default/JwtBearerClientAssertionSecretParser.cs
  src/IdentityServer4/src/Validation/Default/MutualTlsSecretParser.cs
  src/IdentityServer4/src/Validation/Default/PostBodySecretParser.cs
Labels: enhancement

#4501 Update authorization code validation to do client binding check before deleting the code in the store
  src/IdentityServer4/src/Validation/Default/TokenRequestValidator.cs
Labels: enhancement

#4499 Allow setting domain on SessionIdCookie #4406
  src/IdentityServer4/src/Configuration/DependencyInjection/Options/AuthenticationOptions.cs
  src/IdentityServer4/src/Services/Default/DefaultUserSession.cs
Labels: enhancement

#4498 fix infinite loop in Token Cleanup after concurrency exception
  src/EntityFramework.Storage/IdentityServer4.EntityFramework.Storage.sln
  src/EntityFramework.Storage/host/ConsoleHost/ConsoleHost.csproj
  src/EntityFramework.Storage/host/ConsoleHost/Program.cs
  src/EntityFramework.Storage/src/TokenCleanup/TokenCleanupService.cs
Labels: bug

#4496 AuthorizeInteractionResponseGenerator : MaxAge does not respect prompt=none
  src/IdentityServer4/src/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/ResponseHandling/AuthorizeInteractionResponseGenerator/AuthorizeInteractionResponseGeneratorTests.cs
Labels: bug

#4577 fix exception with prompt=login
  src/IdentityServer4/src/Extensions/ValidatedAuthorizeRequestExtensions.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
Labels: bug

#4597 ClientId no longer exists on this object.
  docs/reference/interactionservice.rst
Labels: docs
