Repository IdentityServer/IdentityServer4, pull requests merged in 2020-05, with the labels that each got.

#4342 Add option to emit scopes as space separated string in JWT (as opposed to array)
  docs/reference/options.rst
  src/IdentityServer4/src/Configuration/DependencyInjection/Options/IdentityServerOptions.cs
  src/IdentityServer4/src/Extensions/TokenExtensions.cs
  src/IdentityServer4/src/Services/Default/DefaultTokenCreationService.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Extensions/JwtPayloadCreationTests.cs
Labels: enhancement

#4343 Add option to set SameSite mode for internal cookies
  docs/reference/options.rst
  src/IdentityServer4/src/Configuration/DependencyInjection/ConfigureInternalCookieOptions.cs
  src/IdentityServer4/src/Configuration/DependencyInjection/Options/AuthenticationOptions.cs
Labels: enhancement

#4352 Emit jti by default
  docs/reference/client.rst
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ClientAssertionClient.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ClientCredentialsClient.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/CustomTokenResponseClients.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ExtensionGrantClient.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ResourceOwnerClient.cs
  src/Storage/src/Models/Client.cs
Labels: enhancement

#4357 Add iat to access tokens
  src/IdentityServer4/src/Extensions/TokenExtensions.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ClientAssertionClient.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ClientCredentialsClient.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/CustomTokenResponseClients.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ExtensionGrantClient.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/ResourceOwnerClient.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Conformance/Basic/CodeFlowTests.cs
Labels: enhancement

#4360 Adapt JWT request validation to latest JAR spec
  src/IdentityServer4/src/Validation/Default/AuthorizeRequestValidator.cs
  src/IdentityServer4/src/Validation/Default/JwtRequestValidator.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Endpoints/Authorize/JwtRequestAuthorizeTests.cs
Labels: enhancement

#4361 Extend JWT token validation to accept space separated scopes
  src/IdentityServer4/src/Validation/Default/TokenValidator.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/AccessTokenValidation.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Labels: enhancement

#4245 Strict redirect uri validator app auth with path
  src/IdentityServer4/src/Validation/Default/StrictRedirectUriValidatorAppAuth.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/StrictRedirectUriValidatorAppAuthValidation.cs
Labels: pinned

#4240 Fix UserLoginFailureEvent raised with interactive=true in resource owner grant flow
  src/IdentityServer4/src/Validation/Default/TokenRequestValidator.cs
Labels: bug

#4292 Update 4_javascript_client.rst
  docs/quickstarts/4_javascript_client.rst
Labels: pinned

#4376 Features/grants enhancements
  .gitignore
  src/EntityFramework.Storage/src/DbContexts/ConfigurationDbContext.cs
  src/EntityFramework.Storage/src/Entities/ApiResource.cs
  src/EntityFramework.Storage/src/Stores/DeviceFlowStore.cs
  src/EntityFramework.Storage/src/Stores/PersistedGrantStore.cs
  src/EntityFramework.Storage/test/IntegrationTests/Stores/ClientStoreTests.cs
  src/EntityFramework.Storage/test/IntegrationTests/Stores/PersistedGrantStoreTests.cs
  src/EntityFramework.Storage/test/IntegrationTests/Stores/ResourceStoreTests.cs
  src/EntityFramework.Storage/test/IntegrationTests/TokenCleanup/TokenCleanupTests.cs
  src/EntityFramework.Storage/test/UnitTests/Mappers/ApiResourceMappersTests.cs
  src/EntityFramework.Storage/test/UnitTests/Mappers/IdentityResourcesMappersTests.cs
  src/EntityFramework/migrations/SqlServer/Configuration/Clients.cs
  src/EntityFramework/migrations/SqlServer/Configuration/ClientsConsole.cs
  src/EntityFramework/migrations/SqlServer/Configuration/ClientsWeb.cs
  src/EntityFramework/migrations/SqlServer/Configuration/Resources.cs
  src/IdentityServer4/host/Configuration/Clients.cs
  src/IdentityServer4/host/Extensions/HostProfileService.cs
  src/IdentityServer4/host/Quickstart/Consent/ConsentController.cs
  src/IdentityServer4/host/Quickstart/Extensions.cs
  src/IdentityServer4/host/Startup.cs
  src/IdentityServer4/src/Configuration/CryptoHelper.cs
  src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Additional.cs
  src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Crypto.cs
  src/IdentityServer4/src/Configuration/DependencyInjection/ConfigureInternalCookieOptions.cs
  src/IdentityServer4/src/Endpoints/Results/AuthorizeResult.cs
  src/IdentityServer4/src/Endpoints/Results/ConsentPageResult.cs
  src/IdentityServer4/src/Endpoints/Results/LoginPageResult.cs
  src/IdentityServer4/src/Models/DeviceFlowAuthorizationRequest.cs
  src/IdentityServer4/src/Models/Messages/AuthorizationRequest.cs
  src/IdentityServer4/src/Services/Default/DefaultDeviceFlowInteractionService.cs
  src/IdentityServer4/src/Services/Default/DefaultIdentityServerInteractionService.cs
  src/IdentityServer4/src/Services/Default/DefaultPersistedGrantService.cs
  src/IdentityServer4/src/Services/IPersistedGrantService.cs
  src/IdentityServer4/src/Stores/Default/DefaultGrantStore.cs
  src/IdentityServer4/src/Stores/Default/DistributedCacheAuthorizationParametersMessageStore.cs
  src/IdentityServer4/src/Stores/Default/QueryStringAuthorizationParametersMessageStore.cs
  src/IdentityServer4/src/Stores/IAuthorizationParametersMessageStore.cs
  src/IdentityServer4/src/Stores/InMemory/InMemoryPersistedGrantStore.cs
  src/IdentityServer4/src/Validation/Default/PrivateKeyJwtSecretValidator.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Common/MockPersistedGrantService.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Extensions/JwtPayloadCreationTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Services/Default/DefaultPersistedGrantServiceTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Stores/InMemoryPersistedGrantStoreTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs
  src/Storage/src/Extensions/IEnumerableExtensions.cs
  src/Storage/src/Extensions/PersistedGrantFilterExtensions.cs
  src/Storage/src/Models/Client.cs
  src/Storage/src/Models/Resource.cs
  src/Storage/src/Stores/IPersistedGrantStore.cs
  src/Storage/src/Stores/PersistedGrantFilter.cs
Labels: enhancement

#4411 make apis that manipulate AuthenticationProperties public
  src/IdentityServer4/src/Extensions/AuthenticationPropertiesExtensions.cs
  src/IdentityServer4/src/Services/Default/DefaultUserSession.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Services/Default/DefaultUserSessionTests.cs
Labels: enhancement

#4390 enhancements to add logout notification service as first class service
  samples/Clients/src/MvcHybridBackChannel/Controllers/LogoutController.cs
  samples/Clients/src/MvcHybridBackChannel/Properties/launchSettings.json
  src/IdentityServer4/host/Configuration/ClientsWeb.cs
  src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Additional.cs
  src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer4/src/Endpoints/EndSessionCallbackEndpoint.cs
  src/IdentityServer4/src/Endpoints/Results/EndSessionCallbackResult.cs
  src/IdentityServer4/src/Extensions/HttpContextExtensions.cs
  src/IdentityServer4/src/Extensions/IUserSessionExtensions.cs
  src/IdentityServer4/src/Hosting/IdentityServerAuthenticationService.cs
  src/IdentityServer4/src/IdentityServerConstants.cs
  src/IdentityServer4/src/Models/Contexts/LogoutNotificationContext.cs
  src/IdentityServer4/src/Services/Default/BackChannelLogoutHttpClient.cs
  src/IdentityServer4/src/Services/Default/DefaultBackChannelLogoutService.cs
  src/IdentityServer4/src/Services/Default/LogoutNotificationService.cs
  src/IdentityServer4/src/Services/IBackChannelLogoutHttpClient.cs
  src/IdentityServer4/src/Services/IBackChannelLogoutService.cs
  src/IdentityServer4/src/Services/ILogoutNotificationService.cs
  src/IdentityServer4/src/Validation/Default/EndSessionRequestValidator.cs
  src/IdentityServer4/src/Validation/Models/EndSessionCallbackValidationResult.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs
  src/IdentityServer4/test/IdentityServer.IntegrationTests/Endpoints/EndSession/EndSessionTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Common/MockHttpContextAccessor.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Common/MockLogoutNotificationService.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Endpoints/EndSession/EndSessionCallbackEndpointTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Endpoints/EndSession/EndSessionCallbackResultTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Endpoints/EndSession/StubBackChannelLogoutClient.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Endpoints/Results/EndSessionCallbackResultTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Services/Default/DefaultIdentityServerInteractionServiceTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/EndSessionRequestValidation/EndSessionRequestValidatorTests.cs
Labels: enhancement

#4428 add consumedtime to persisted grant and refresh token
  samples/Clients/src/MvcHybridBackChannel/Controllers/HomeController.cs
  src/EntityFramework.Storage/migrations/SqlServer/Migrations/ConfigurationDb.sql
  src/EntityFramework.Storage/migrations/SqlServer/Migrations/ConfigurationDb/20200522172542_Config.Designer.cs
  src/EntityFramework.Storage/migrations/SqlServer/Migrations/ConfigurationDb/20200522172542_Config.cs
  src/EntityFramework.Storage/migrations/SqlServer/Migrations/PersistedGrantDb.sql
  src/EntityFramework.Storage/migrations/SqlServer/Migrations/PersistedGrantDb/20200522172538_Grants.Designer.cs
  src/EntityFramework.Storage/migrations/SqlServer/Migrations/PersistedGrantDb/20200522172538_Grants.cs
  src/EntityFramework.Storage/migrations/SqlServer/Migrations/PersistedGrantDb/PersistedGrantDbContextModelSnapshot.cs
  src/EntityFramework.Storage/migrations/SqlServer/buildschema.bat
  src/EntityFramework.Storage/src/Entities/PersistedGrant.cs
  src/EntityFramework.Storage/src/TokenCleanup/TokenCleanupService.cs
  src/EntityFramework.Storage/test/UnitTests/Mappers/PersistedGrantMappersTests.cs
  src/EntityFramework/migrations/SqlServer/Configuration/ClientsWeb.cs
  src/EntityFramework/migrations/SqlServer/Configuration/Resources.cs
  src/IdentityServer4/src/Stores/Default/DefaultGrantStore.cs
  src/IdentityServer4/src/Stores/Default/DefaultRefreshTokenStore.cs
  src/Storage/src/Models/PersistedGrant.cs
  src/Storage/src/Models/RefreshToken.cs
Labels: enhancement

#4439 namespace cleanup/refactor in host (to support templates)
  src/IdentityServer4/host/Quickstart/Account/AccountController.cs
  src/IdentityServer4/host/Quickstart/Account/AccountOptions.cs
  src/IdentityServer4/host/Quickstart/Account/ExternalController.cs
  src/IdentityServer4/host/Quickstart/Account/ExternalProvider.cs
  src/IdentityServer4/host/Quickstart/Account/LoggedOutViewModel.cs
  src/IdentityServer4/host/Quickstart/Account/LoginInputModel.cs
  src/IdentityServer4/host/Quickstart/Account/LoginViewModel.cs
  src/IdentityServer4/host/Quickstart/Account/LogoutInputModel.cs
  src/IdentityServer4/host/Quickstart/Account/LogoutViewModel.cs
  src/IdentityServer4/host/Quickstart/Account/RedirectViewModel.cs
  src/IdentityServer4/host/Quickstart/Consent/ConsentController.cs
  src/IdentityServer4/host/Quickstart/Consent/ConsentInputModel.cs
  src/IdentityServer4/host/Quickstart/Consent/ConsentOptions.cs
  src/IdentityServer4/host/Quickstart/Consent/ConsentViewModel.cs
  src/IdentityServer4/host/Quickstart/Consent/ProcessConsentResult.cs
  src/IdentityServer4/host/Quickstart/Consent/ScopeViewModel.cs
  src/IdentityServer4/host/Quickstart/Device/DeviceAuthorizationInputModel.cs
  src/IdentityServer4/host/Quickstart/Device/DeviceAuthorizationViewModel.cs
  src/IdentityServer4/host/Quickstart/Device/DeviceController.cs
  src/IdentityServer4/host/Quickstart/Diagnostics/DiagnosticsController.cs
  src/IdentityServer4/host/Quickstart/Diagnostics/DiagnosticsViewModel.cs
  src/IdentityServer4/host/Quickstart/Extensions.cs
  src/IdentityServer4/host/Quickstart/Grants/GrantsController.cs
  src/IdentityServer4/host/Quickstart/Grants/GrantsViewModel.cs
  src/IdentityServer4/host/Quickstart/Home/ErrorViewModel.cs
  src/IdentityServer4/host/Quickstart/Home/HomeController.cs
  src/IdentityServer4/host/Quickstart/SecurityHeadersAttribute.cs
  src/IdentityServer4/host/Quickstart/TestUsers.cs
  src/IdentityServer4/host/Startup.cs
  src/IdentityServer4/host/Views/Device/UserCodeConfirmation.cshtml
  src/IdentityServer4/host/Views/_ViewImports.cshtml
  src/IdentityServer4/src/Configuration/IdentityServerApplicationBuilderExtensions.cs
  src/IdentityServer4/src/Endpoints/Results/EndSessionCallbackResult.cs
  src/IdentityServer4/src/Services/Default/DefaultJwtRequestUriHttpClient.cs
  src/IdentityServer4/src/Services/Default/DefaultUserSession.cs
  src/IdentityServer4/src/Validation/Models/ValidatedRequest.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Endpoints/EndSession/EndSessionCallbackEndpointTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Endpoints/EndSession/EndSessionCallbackResultTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Endpoints/Results/EndSessionCallbackResultTests.cs
  src/IdentityServer4/test/IdentityServer.UnitTests/Validation/EndSessionRequestValidation/EndSessionRequestValidatorTests.cs
Labels: enhancement

#4451 Update resource docs
  docs/topics/resources.rst
  samples/Clients/src/ConsoleClientCredentialsFlowPostBody/Program.cs
  samples/Clients/src/ConsoleCustomGrant/Program.cs
  samples/Clients/src/ConsoleEphemeralMtlsClient/Program.cs
  samples/Clients/src/ConsoleHybridWithPkce/Program.cs
  samples/Clients/src/ConsoleIntrospectionClient/Program.cs
  samples/Clients/src/ConsoleMTLSClient/Program.cs
  samples/Clients/src/ConsolePrivateKeyJwtClient/Program.cs
  samples/Clients/src/ConsoleResourceOwnerFlow/Program.cs
  samples/Clients/src/ConsoleResourceOwnerFlowPublic/Program.cs
  samples/Clients/src/ConsoleResourceOwnerFlowReference/Program.cs
  samples/Clients/src/ConsoleResourceOwnerFlowRefreshToken/Program.cs
  samples/Clients/src/JsOidc/wwwroot/app.js
  samples/Clients/src/MvcAutomaticTokenManagement/Startup.cs
  samples/Clients/src/MvcCode/Startup.cs
  samples/Clients/src/MvcHybridBackChannel/Startup.cs
  src/IdentityServer4/host/Configuration/ClientsConsole.cs
  src/IdentityServer4/host/Configuration/ClientsWeb.cs
  src/IdentityServer4/host/Configuration/Resources.cs
Labels: docs
